### ISSUE TITLE
Better specific task example

### ISSUE THREAD

**Issue by enormandeau** [ehamberg/gtdguide#2]
First, I love your GTD guide.

However, I would argue that "call Ada 25 August to discuss cheesecake recipe" is an inherently sexist example and suggest to change it to anything else that does not assume gendered roles or other types of biases.

Take care

**Comment by ehamberg** [comment]
Hi @enormandeau. Thank you for bringing this to my attention. As part of a general text clean-up I have tweaked the examples, including the one you mentioned.
